SELECT OD.ORDER_DETAIL_CODE,
	OH.RETAILER_NAME,
	OD.ORDER_NUMBER,
	CONVERT(DATE, OH.ORDER_DATE) AS ORDER_DATE,
	SS.SALES_STAFF_CODE,
	SS.FIRST_NAME,
	SS.LAST_NAME,
	P.PRODUCT_NUMBER,
	P.PRODUCT_NAME,
	PT.PRODUCT_TYPE_EN,
	OD.QUANTITY
FROM ORDER_DETAILS OD
	LEFT JOIN PRODUCT P ON OD.PRODUCT_NUMBER = P.PRODUCT_NUMBER
	LEFT JOIN ORDER_HEADER OH ON OD.ORDER_NUMBER = OH.ORDER_NUMBER
	LEFT JOIN PRODUCT_TYPE PT ON P.PRODUCT_TYPE_CODE = PT.PRODUCT_TYPE_CODE
	LEFT JOIN SALES_STAFF SS ON OH.SALES_STAFF_CODE = SS.SALES_STAFF_CODE
ORDER BY OD.ORDER_DETAIL_CODE