SELECT RI.RETURN_CODE,
	CONVERT(DATE, RI.RETURN_DATE) AS RETURN_DATE,
	OH.RETAILER_NAME,
	OH.ORDER_NUMBER,
	RI.ORDER_DETAIL_CODE,
	SS.SALES_STAFF_CODE,
	SS.FIRST_NAME,
	SS.LAST_NAME,
	OD.PRODUCT_NUMBER,
	P.PRODUCT_NAME,
	PT.PRODUCT_TYPE_EN,
	RR.REASON_DESCRIPTION_EN,
	RI.RETURN_QUANTITY
FROM RETURNED_ITEM RI
	LEFT JOIN RETURN_REASON RR ON RI.RETURN_REASON_CODE = RR.RETURN_REASON_CODE
	LEFT JOIN ORDER_DETAILS OD ON RI.ORDER_DETAIL_CODE = OD.ORDER_DETAIL_CODE
	LEFT JOIN PRODUCT P ON OD.PRODUCT_NUMBER = P.PRODUCT_NUMBER
	LEFT JOIN PRODUCT_TYPE PT ON P.PRODUCT_TYPE_CODE = PT.PRODUCT_TYPE_CODE
	LEFT JOIN ORDER_HEADER OH ON OD.ORDER_NUMBER = OH.ORDER_NUMBER
	LEFT JOIN SALES_STAFF SS ON OH.SALES_STAFF_CODE = SS.SALES_STAFF_CODE